// packages/web-components/src/index.tsx
class BoxElement extends HTMLElement {
  static observedAttributes = [
    "g",
    "m",
    "p",
    "inline",
    "wrap",
    "shrink",
    "align",
    "justify",
    "fullWidth",
    "fullHeight",
    "debug",
  ];

  constructor() {
    super();
    this.attachShadow({ mode: "open" });
  }

  attributeChangedCallback(
    name: string,
    _: string | null,
    newValue: string | null
  ) {
    if (newValue !== null) {
      this.style.setProperty(`--${name}`, newValue);
    }
    this.updateStyles();
  }

  connectedCallback() {
    this.updateStyles();
    this.render();
  }

  updateStyles() {
    this.style.display = this.hasAttribute("inline") ? "inline-flex" : "flex";
    this.style.flexWrap = this.hasAttribute("wrap") ? "wrap" : "nowrap";
    this.style.flexShrink = this.hasAttribute("shrink") ? "0" : "";
    this.style.width = this.hasAttribute("fullWidth") ? "100%" : "";
    this.style.height = this.hasAttribute("fullHeight") ? "100%" : "";
    this.style.outline = this.hasAttribute("debug") ? "1px solid red" : "";
    this.style.gap = this.getAttribute("g") || "";
    this.style.margin = this.getAttribute("m") || "";
    this.style.padding = this.getAttribute("p") || "";
    this.style.justifyContent = this.getAttribute("justify") || "";
    this.style.alignItems = this.getAttribute("align") || "";
  }

  render() {
    if (this.shadowRoot) {
      this.shadowRoot.innerHTML = `<slot></slot>`;
    }
  }
}

export class XElement extends BoxElement {
  connectedCallback() {
    super.connectedCallback();
    this.style.flexDirection = "row";
  }
}

export class YElement extends BoxElement {
  connectedCallback() {
    super.connectedCallback();
    this.style.flexDirection = "column";
  }
}

customElements.define("x-box", XElement);
customElements.define("y-box", YElement);

// packages/styled/src/index.tsx
"use client";
import { DefaultTheme, styled } from "styled-components";

export interface BoxProps {
  g?: string;
  m?: string;
  p?: string;
  inline?: boolean;
  wrap?: boolean;
  shrink?: boolean;
  align?: string;
  alignItems?: string;
  justify?: string;
  justifyContent?: string;
  fullWidth?: boolean;
  fullHeight?: boolean;
  debug?: boolean;
  padding?: string;
  gap?: string;
  margin?: string;
}

interface ExtendedTheme extends DefaultTheme {
  xyDebug?: boolean;
}

export const Box = styled.div.withConfig({
  shouldForwardProp: (prop) =>
    ![
      "g",
      "gap",
      "m",
      "margin",
      "p",
      "padding",
      "inline",
      "wrap",
      "shrink",
      "align",
      "alignItems",
      "justify",
      "justifyContent",
      "fullWidth",
      "fullHeight",
      "debug",
    ].includes(prop),
})<BoxProps>`
  display: ${({ inline }) => (inline ? "inline-flex" : "flex")};
  ${({ p, padding }) =>
    p || padding ? `padding: ${p || padding}` : undefined};
  ${({ g, gap }) => (g || gap ? `gap: ${g || gap}` : undefined)};
  ${({ m, margin }) => (m || margin ? `margin: ${m || margin}` : undefined)};
  ${({ wrap }) => (wrap ? "flex-wrap: wrap;" : undefined)};
  ${({ justify, justifyContent }) =>
    justify || justifyContent
      ? `justify-content: ${justify || justifyContent};`
      : undefined};
  ${({ align, alignItems }) =>
    align || alignItems ? `align-items: ${align || alignItems};` : undefined};
  ${({ shrink }) => (shrink ? `flex-shrink: 0;` : undefined)};
  ${({ fullWidth }) => (fullWidth ? `width: 100%;` : undefined)};
  ${({ fullHeight }) => (fullHeight ? `height: 100%;` : undefined)};
  ${({ theme, debug }: { theme: ExtendedTheme; debug?: boolean }) =>
    (theme?.xyDebug || debug) && `outline: 1px solid red;`}
`;

export const X = styled(Box)`
  flex-direction: row;
  ${({ align = "center" }) => (align ? `align-items: ${align};` : undefined)};
`;

export const Y = styled(Box)`
  flex-direction: column;
`;
